# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='KOSDAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('index', models.FloatField()),
                ('index_change', models.FloatField()),
                ('pct_change', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('signal', models.CharField(blank=True, choices=[('B', 'Buy'), ('S', 'Sell'), ('H', 'Hold')], max_length=1, null=True)),
                ('signal_days', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, choices=[('A', 'Strong'), ('B', 'Normal'), ('C', 'Weak')], max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KOSPI',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('index', models.FloatField()),
                ('index_change', models.FloatField()),
                ('pct_change', models.FloatField()),
                ('volume', models.BigIntegerField()),
                ('signal', models.CharField(blank=True, choices=[('B', 'Buy'), ('S', 'Sell'), ('H', 'Hold')], max_length=1, null=True)),
                ('signal_days', models.IntegerField(blank=True, null=True)),
                ('rating', models.CharField(blank=True, choices=[('A', 'Strong'), ('B', 'Normal'), ('C', 'Weak')], max_length=1, null=True)),
            ],
        ),
    ]
