# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-15 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HalfYearSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('mom_rank', models.IntegerField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('vol_rank', models.IntegerField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('corr_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MonthSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('mom_rank', models.IntegerField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('vol_rank', models.IntegerField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('corr_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuarterSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('mom_rank', models.IntegerField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('vol_rank', models.IntegerField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('corr_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TwoWeekSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('mom_rank', models.IntegerField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('vol_rank', models.IntegerField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('corr_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WeekSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('mom_rank', models.IntegerField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('vol_rank', models.IntegerField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('corr_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='YearSpecs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('date', models.CharField(max_length=8)),
                ('momentum', models.FloatField(blank=True, null=True)),
                ('mom_rank', models.IntegerField(blank=True, null=True)),
                ('volatility', models.FloatField(blank=True, null=True)),
                ('vol_rank', models.IntegerField(blank=True, null=True)),
                ('correlation', models.FloatField(blank=True, null=True)),
                ('corr_rank', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
