# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='portfolio_type',
            field=models.CharField(blank=True, choices=[('S', 'Stock'), ('CS', 'Cash + Stock')], max_length=2, null=True),
        ),
    ]
