# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-02 15:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_portfoliodiagnosis'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayPortfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.CharField(max_length=8)),
                ('portfolio', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
    ]
