# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-11-30 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20171130_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='capital',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
